name: Build MagnetArgs

on:
  push:
    tags:
      - '0.*'

jobs:
  build:
    runs-on: windows-2022

    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        source-url: https://nuget.pkg.github.com/ArtTorres/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      working-directory: ./src
      run: dotnet build --configuration Release

    - name: Test
      working-directory: ./src
      run: dotnet test --no-build

    - name: Zip
      working-directory: ./src
      run: 7z a MagnetArgs_${{github.ref_name}}_bin.zip ./bin/Release/*.* -x!*.*nupkg
        
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{github.ref_name}}"
        prerelease: false
        title: "MagnetArgs - v${{github.ref_name}}"
        files: ./src/MagnetArgs_${{github.ref_name}}_bin.zip
    
    - name: Create Github Package
      working-directory: ./src/bin/Release
      env:
        API_KEY: ${{secrets.GITHUB_TOKEN}}
      run: dotnet nuget push "MagnetArgs.${{github.ref_name}}.nupkg"

    - name: Release NuGet Package
      working-directory: ./src/bin/Release
      env:
        API_KEY: ${{secrets.AKN}}
      run: dotnet nuget push "MagnetArgs.${{github.ref_name}}.nupkg" --api-key "%API_KEY%" --source https://api.nuget.org/v3/index.json
